---
title: "Trump Approval by Education"
author: "Ansley Hatcher"
date: "9/15/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r pressure, echo=FALSE, message=FALSE}
library(tidyverse)
library(here)
library(forcats)
load(here('data/ces-2020/cleaned-CES.RData'))

custom.col <- c("#FFDB6D", "#C4961A", "#F4EDCA", 
                "#D16103", "#C3D7A4", "#52854C", "#4E84C4", "#293352")

p <- ces %>%
  filter(!is.na(trump_approval)) %>%
  mutate(educ = fct_relevel(educ, "No HS", "High school graduate", "Some college", "2-year", "4-year", "Post-grad")) %>%
  ggplot() +
  geom_bar(mapping = aes(y = trump_approval,
                         x = ..prop..,
                         group = 1,
                         # check out https://sebastiansauer.github.io/percentage_plot_ggplot2_V2/ (Way 4)
                         fill = factor(..y..))) +
  theme_classic() +
  facet_wrap(~educ) +
  labs (x = 'Proportion of Respondents', y = 'Trump Approval', title = 'Trump Approval by Education Level', caption = 'Data from 2020 Cooperative Election Study') +
  theme(legend.position = 'none') +
  scale_fill_manual(values = custom.col)
p
```
