---
title: "Week 6: Causality"
author: Joe Ornstein

echo: true
message: false
warning: false
bibliography: references.bib
---

# Reading

# Problem Set

In this week's problem set, we will practice some of the calculus skills we developed last week, and show how it connects to optimization problems in both statistics and formal theory.

1.  A dictator is deciding how much tax revenue to steal for himself and how much to give to his generals. He can steal some fraction of revenue $x$ between 0 and 1. If he steals all of it $(x = 1)$, then his generals will get mad, overthrow him, and he gets nothing. If he gives everything to his generals $(x = 0)$, then his generals are happy, don’t overthrow him, but he still gets nothing because he gave away all the loot. If the probability that the generals leave him in place equals $1 − x$, how much should the dictator steal to maximize his expected happiness (probability of staying in power × the amount of money stolen)?
2.  Suppose you have three data points: $x_1$, $x_2$, and $x_3$. Find the value $m$ that minimizes the sum of squared errors $f(m)$:

$$
f(m) = (x_1-m)^2 + (x_2 - m)^2 + (x_3-m)^2
$$

3.  Consider the following linear model. If you increase $X$ by 1 unit, what happens to $Y$?

$$
Y = 2X + 5Z + 4XZ + \varepsilon
$$

4.  
5.  

# Additional Resources

-   @huntington-kleinEffectIntroductionResearch2021, a friendly yet thorough introduction to causal inference with observational data (free version online [here](https://theeffectbook.net/)).
