---
title: "POLS 7012: Introduction to Political Methodology"
author: 
  - name: Joe Ornstein
    email: jornstein@uga.edu
    orcid: 0000-0002-5704-2098
date: today
---

Welcome to our course website! Here you can find links to everything you'll need this semester:

-   The course syllabus (this page or in [PDF](syllabus/POLS-7012-syllabus.pdf))

-   Reading assignments, problem sets, and class notes can be found in the **Schedule** drop-down menu on the upper-right; click each link to access that week's content.

-   Submit assignments at our course [eLC page](https://uga.view.usg.edu/d2l/home/3639787) (mortarboard icon in the upper right).

-   You can read, annotate, and ask questions about each week's readings on our course [Perusall](https://app.perusall.com/courses/introduction-to-political-methodology/) page (book icon in the upper right).[^1]

-   I will post code and data on the course [GitHub repository](https://github.com/joeornstein/intro-political-methodology) (the octocat icon in the upper right).

[^1]: Visit eLC for the Perusall access code.

# Syllabus

This course will introduce the foundational mathematical and computational skills you will need to conduct and evaluate political science research. During the first half of the semester (Part 1: Fundamentals), we discuss the techniques that political scientists use to address three fundamental problems of scientific inquiry: measurement, causal inference, and sampling. In the second half of the semester (Part 2: Applications), we apply what we've learned to a series of miniature research projects, focusing on the practical computational skills you need to work with data. By the end of the semester, you will be armed with the necessary tools to tackle the more advanced material that makes up the rest of our graduate methods sequence.

## Course Objectives

By the end of this course, you will be able to:

-   Confidently work with data using the `R` programming language

-   Create beautiful and informative data visualizations

-   Organize your work so that it is transparent and reproducible

-   Build basic statistical models and estimate their parameters from data

-   Communicate uncertainty around your estimates

-   Identify research designs that credibly address three fundamental challenges of social science: measurement, causal inference, and sampling.

## Assignments & Grading

Each week I will assign 1-2 chapters of reading and a problem set, both due at noon the day of class. Feel free to consult your classmates with questions about the problem sets, but I expect you to submit your answers individually. **Resist the temptation to copy-paste your classmates' code.** You are much more likely to learn if you type your responses yourself. Each problem set contains a **Bonus** problem that will require you to conduct some independent research beyond that week's reading. Problem sets will be graded pass/fail, where a passing grade indicates that you have correctly solved over 70% of the problems.

The semester will culminate with each student completing an independent research project. During the final two weeks, students will present an original analysis of a dataset of their choice. To meet expectations, the project should address in a satisfying way issues relating to measurement, causal inference, and sampling, and students should submit code and a codebook that allows others to replicate their analysis from the raw dataset. Within 48 hours of your presentation, I will provide you a list of revisions that I think would improve the research. Completing these revisions before the end of finals period is a requirement for earning an A- or A in the course. Students wishing to earn an A will—in addition to the presentation, code, and codebook—submit a final paper that includes an abstract, brief literature review, and discussion of their findings.

The final letter grade you earn for the semester will be determined based on the number of problem sets you complete that meet expectations, the number of bonus problems you successfully complete, and your performance on the final project. Consult the table below for the minimum requirements for each letter grade. To earn a given letter grade, you must complete the requirements for that grade and all the grades below it, and students must at least meet the requirements for a C to pass the course.

| Letter Grade | Problem Sets | Bonus Problems | Final Project                |
|--------------|--------------|----------------|------------------------------|
| A            | 10           | 8              | Submit a final paper         |
| A-           | 9            | 5              | Complete requested revisions |
| B+           | 8            | 2              | Code successfully replicates |
| B            | 7            | 0              | Provide code and codebook    |
| C            | 6            | 0              | Present final project        |

## Office Hours and Email Policy

I will be available for students to drop in and chat every Thursday afternoon from 2-4pm. My office is Baldwin 304C. If you send me an email, please allow me 24 hours to respond. Like many professors, my inbox is pretty overloaded. Also, I have small children, so it's my policy to not check email after 5pm or on weekends. You should feel free to seek assistance from the senior graduate students staffing the SPIA Methods Helpdesk. You can email them questions at **spia-methods-help\@uga.edu**.

## Books

Our readings will come from the two books listed below. The first book (DAFSS) must be purchased---either in hard-copy or through the course [Perusall](https://app.perusall.com/courses/introduction-to-political-methodology/) site---but the second (R4DS) is freely available online.

-   **DAFSS**: Llaudet, Elena & Imai, Kosuke (2022). [Data Analysis for Social Science: A Friendly and Practical Introduction](https://press.princeton.edu/books/paperback/9780691199436/data-analysis-for-social-science). Princeton University Press.

-   **R4DS**: Wickham, H., Cetinkaya-Rundel, M., & Grolemund, G., (2023). [R For Data Science: Import, Tidy, Transform, Visualize, and Model Data](https://r4ds.hadley.nz/), 2nd Edition. O'Reilly Media, Inc.

## Schedule

See the **Schedule** drop-down menu in the upper right for a complete list of each week's objectives, assignments, and class notes.
