---
title: "Week 1"
description: |
  Getting all the software up and running
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

This week, we will familiarize ourselves with a suite of software that will make life as a social scientist so much nicer -- tools for managing your data, your references, and your knowledge. Make sure you've completed everything from the [Getting Started](index.html#getting-started) section on the home page.

## Reading Assignments

Before Week 2, please read and annotate the following:

- [Healy Preface](https://socviz.co/index.html#preface) (and complete the package installation instructions at the bottom)
- [Healy Chapter 2](https://socviz.co/gettingstarted.html)
- [Healy Chapter 3](https://socviz.co/makeplot.html#makeplot)

Optional:

- [Healy Chapter 1](https://socviz.co/lookatdata.html)

## Problem Set

Find the file `R/week-01/problem-set-1.Rmd` in our GitHub repository. Open it and make the following changes:

1. Edit the metadata so that you are the author.
2. Follow the instructions in the comments of each code chunk.
3. Knit to PDF.
4. Submit the knitted PDF document to eLC by our next class.[^1]

[^1]: All problem sets due by the *following* week's class (so this one is due before our second class). Feel free to work together on problem sets, but I encourage you to type out the solutions yourself instead of copying-pasting from others. You can't learn this stuff without doing it. 