---
title: "Week 3"
description: |
  After this week, your charts will be *extremely* fancy
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```


## Reading Assignments

Next week we'll start learning how to tidy up messy datasets. In preparation, please read and annotate the following:

- [R4DS Chapter 1: Introduction](https://r4ds.had.co.nz/introduction.html)
-   [R4DS Chapter 9: Wrangle](https://r4ds.had.co.nz/wrangle-intro.html)
-   [R4DS Chapter 11: Import](https://socviz.co/refineplots.html) (skip sections 11.3 and 11.4)
- [R4DS Chapter 12: Tidy Data](https://r4ds.had.co.nz/tidy-data.html)
- [R4DS Chapter 13: Relational Data](https://r4ds.had.co.nz/relational-data.html) (skip sections 13.5-13.7)
-   [Healy Chapter 8](https://socviz.co/refineplots.html)

Optional:

- I'm assigning what I think are the crucial chapters of R4DS, but if you really want to get deep into `R` programming, feel free to look over the chapters we skipped. In particular, the chapter on "Strings" if you want to work with text data, and "Dates & Times" if you want to work with time series.

## Problem Set

Take your visualization from last week and refine it using the techniques we learned in Week 3. Submit a PDF from a knitted RMarkdown document, containing your visualization and a page or two of prose explaining your research question and findings. Incude a bibliography generated by the Zotero integration, and submit both your PDF and `.Rmd` file.