---
title: "Week 10"
description: |
  Finding Front Doors
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
```

This week, the instrumental variable approach to causal inference. We'll talk experiments, two-stage least squares, and regression discontinuity designs.

## Further Reading

If you're interested in learning more about these methods and don't want to wait until I teach a standalone class on causal inference, check out chapters 19 and 20 in @huntington-klein2021.

## Problem Set

In a knitted R script (or Rmd), complete the following problems:

1.  Using the replication data from the @cohn2019 wallet experiment, estimate the average treatment effect of money for (a) men only, (b) women only, (c) public institutions only, (d) people who seemed to understand what the experimenter was saying. Do there seem to be heterogeneous treatment effects? Can we interpret these estimates as causal? Why or why not?
2.  Estimate the incumbency advantage/disadvantage in other (non-Brazil) Latin American countries from the @klanja2017 dataset. Plot the data, faceting by country.
