---
title: 'POLS 7012: Problem Set 5'
author: "Joe Ornstein"
date: "Due September 30, 2020"
output:
  pdf_document: default
  html_document: default
urlcolor: blue
---

```{r setup, include=FALSE}
# For problem set, echo and eval = FALSE
# For answer key, echo and eval = TRUE
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
```


## Instructions

Do democracies or autocracies devote a greater share of national resources to the military? In this problem set, you will test your new skills importing, tidying, transforming, and summarizing data to answer this question. You will need two datasets:

- The [Polity 5 Time Series](https://www.systemicpeace.org/inscrdata.html) for the "Polity Score" of each country over time (-10 is strongly autocratic, +10 is strongly democratic).
- The [National Material Capabilities](https://correlatesofwar.org/data-sets/national-material-capabilities) dataset, for information on each country's military capabilities. 

As you will see, there can be more than one way to answer this question. But our approach will be to compute the number of military personnel by country as a share of the total population, and compare that value for democracies and autocracies over time. To do so, complete the following steps:

1. Download the two datasets and read them into `R`.

2. Keep only the variables you need, and merge the two datasets.^[Consult the codebooks (included at the links above) to determine which variables to use as keys for the merge, and which variables represent your outcomes of interest.]

3. Create a new variable equal to the number of military personnel per 1,000 people in the country's total population.

4. Create a new `regime` variable, coding countries as a "Democracy" if their Polity2 score is greater than five and an "Autocracy" otherwise.

5. Compute the average share of the population in the military for autocracies and democracies over time (`group_by` regime type and year), as well as the number of countries in each category (`summarize` function). Assign this new grouped dataframe to an object.

6. Plot your results (`geom_line` would be nice).

