---
title: "Problem Set 10 (Answer Key)"
author: "Joe Ornstein"
format: pdf
editor: visual
---

## 

1.  Load the data

```{r}
library(tidyverse)
library(here)

load( here('data/ces-2020/cleaned-CES.RData') )

```

2\.

```{r}
# recode as 0-1 variable
ces <- ces |> 
  mutate(china_tariffs = as.numeric(china_tariffs == 'Support'))

ces |> 
  summarize(pct_support = mean(china_tariffs))

# drop out the people who didn't respond to that question
ces <- ces |> 
  filter(!is.na(china_tariffs))

ces |> 
  summarize(pct_support = mean(china_tariffs))

```

3.  What's the difference in tariff support for men and women?

```{r}

ces |> 
  group_by(gender) |> 
  summarize(pct_support = mean(china_tariffs))

```

4.  Write a function that samples 100 respondents and computes the difference in means.

```{r}

diff_in_means <- function(sample_size = 100){
  
  small_ces <- ces |> 
    slice_sample(n = sample_size) |> 
    mutate(male = as.numeric(gender == 'Male'))
  
  
  linear_model <- lm(china_tariffs ~ male, 
                     data = small_ces)
  
  
  return(linear_model$coefficients['male'])
  
}

diff_in_means()

diff_in_means()
```

5.  Generate sampling distribution

```{r}
sampling_distribution <- replicate(20000,
                                   diff_in_means())
```

6.  Plot it

```{r}
hist(sampling_distribution)

ggplot(mapping = aes(x=sampling_distribution)) +
  geom_histogram(color = 'black') +
  theme_classic() +
  labs(x = 'Sample Difference in Means')

```

What's the expected value?

```{r}
mean(sampling_distribution)
```

Standard error?

```{r}
sd(sampling_distribution)
```
